### ISSUE TITLE
Portal istnieje, brak zapisu w pliku

### ISSUE THREAD

**Issue by xNorbig** [piratjsk/Prtls#2]
Istnieje portal o nazwie "nazwa", można się normalnie do niego teleportować, a w pliku `portals.yml` nic nie ma o tym portalu.
W pliku jest `storage: yaml`

**Comment by piratjsk** [comment]
Portale są aktualnie zapisywane tylko podczas wyłączania pluginu albo po użyciu komendy `portals save`.
